### ISSUE TITLE
Live stream reading and annotating @slifty's masters thesis

### ISSUE THREAD

**Issue by knowtheory** [BadIdeaFactory/truthgoggles#10]
Check with @louh whether this is a thing we can do as a general BIFFUD thing.

**Comment by louh** [comment]
Tell me more? (Should we have a BIFFUD Twitch channel?)

**Comment by slifty** [comment]
I'm going to spin up a BIFFUD twitch channel this afternoon since we have a few stream-related things going down these days...

**Comment by knowtheory** [comment]
@louh, so, [in the spirit of putting as much of @slifty's past on display](https://vimeo.com/5060010) for everyone to appreciate, i thought that it would be fun (as well as informative) to read through Dan's thesis, which is about Truth Goggles in it's original incarnation and about the landscape & opportunities for talking about truth & fact (checking) now.

**Comment by slifty** [comment]
UGHHHHHHhhhhhhhhhhhhhhhhh

**Comment by louh** [comment]
lolz

**Comment by slifty** [comment]
Update: [BIFFUD twitch channel exists!](http://twitch.tv/biffud) and is generally great.

I don't think anybody actually wants to live stream my thesis.
