### ISSUE TITLE
Set up a database system

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/truthgoggles#26]
We need a place to store our data.  To do this we need to:

- [x] Decide on a database system (Mongo vs. Postgres)
- [ ] Set up that database system in the repository
- [ ] Set up niceties to go along with the database system (e.g. migrations, or whatever the migration equivalent for NoSQL is... uhhhhhhhhh)

**Comment by slifty** [comment]
Update here: We decided on postgres because apparently only poor ignorant fools use mongo anymore!

We'll use sequelize as our ORM.

**Comment by slifty** [comment]
I put some time and energy into setting up sequelize only to realize that all the boilerplate logic is written in ES5 and needs to be rewritten in ES6.

If someone has the will and inclination to set up sequelize using ES6 instead of their old boilerplates lets do that.

**Comment by crupar** [comment]
I'll be scrapping the old boilerplate and setting up something new and shiny later today.
