### ISSUE TITLE
Implement schema for Modifying Language

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/truthgoggles#31]
The experiment described in #17 will have data that needs to be stored.  We need to define the nature of that data and set up migrations.

Lets use the wiki to document the proposed schema for now; eventually we will do that through migrations and models, but we need #26 before we can start doing that kind of thing.

**Comment by slifty** [comment]
This will be easier to discuss as a PR, but we need #26 wrapped for that (it sounds like we're almost there...)

In the mean time, here are some notes on a potential schema idea, to be discussed by voice.

```
users
- id

credible_content
- id
- base_url
- title
- author
- body

concepts
- id
- display_name (what we might show a user)
- detection_pattern (regular expression to detect the pattern in a corpus)

referenced_concepts (concepts that appear in credible content)
- id
- content_id
- concept_id
- disposition (+, 0, -)

personal_preferences
- id
- user_id
- concept_id
- disposition (+, 0, -)

alternative_phrases
- id
- phrase
- alternative
- toggle_concept (concept where preference might trigger the alternative)
- toggle_disposition (nature of the disposition that might trigger the toggle; +, 0, -)

tone_modifiers
- id
- modifier_pattern (pattern that will combine with a concept to modify the tone)
- toggle_concept
```

**Comment by knowtheory** [comment]
Okay, so is this taken care of now through #36?

**Comment by knowtheory** [comment]
Okay here's a list of some things i'd like to know more about, and if we have tickets accounting for any of the following:

- [ ] interface / view for (er,) viewing an article/factcheck/content (could be stylistically plain)
- [ ] mechanism for highlighting subsets of text w/in a text display (yay string annotation)
- [ ] a linter to identify substrings w/in article/factcheck/content
- [ ] interface/ view for user to be able to paste text into a box to be linted.
- [ ] interface / view for listing items to highlight/lint (index of fact checks)
-------------------------
- [ ] input bar for URL for user to submit a page to be scraped & linted?

**Comment by slifty** [comment]
#36 just set up the scaffolding to allow us to implement the schema.  #38 implements a single table of the schema (I should have tagged this issue in there).

Point being: this is not taken care of yet!

As to the other items, I don't believe there are issues created for interfaces.  I suggest @crupar take some time to open some issues (or even just one issue capturing her plans for the linter) since I think that's been her area of focus so far.  (obviously @knowtheory you are welcome to as well, to kick off the discussion)

**Comment by knowtheory** [comment]
Awesome, thanks for the heads up @slifty.  I see that @crupar set up #39, i'll add that up to the tracking thing i've got there (normally i'd stick it in the body of a ticket, and in fact i might migrate all that stuff up).

I also normally just do a cut line for things that gotta be shipped and which things can fall after the shipping point.

**Comment by slifty** [comment]
The schema we're targeting has changed now that we have nailed down the wireframes, so I am actually going to close this particular issue given that fact.  I'm sure there will be a new one soon.
