### ISSUE TITLE
Set up linting

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/truthgoggles#32]
We haven't written any code yet, so now is the perfect time to set up linting and nail down code styles for the project.  I believe eslint is what we're going to want, and unless others hate this idea I'd propose we go for the gold and use the airbnb ruleset.

Also, no semicolons...? eh? eh?

**Comment by Laurian** [comment]
create react app gives you a set of defaults too, use those and move on, stop fiddling with dotfiles

**Comment by slifty** [comment]
Oh duh, makes sense that would be there.
I must have just not actually run the linter!

cc @crupar on the above.
