### ISSUE TITLE
UX Design for modifying language experiment

### ISSUE THREAD

**Issue by crupar** [BadIdeaFactory/truthgoggles#39]
An interface is needed for this!  They have been [wireframed](docs/1_language_check.pdf) but here are some screen shots:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/208884/50574551-9c5d1400-0db8-11e9-8c19-d1a6eeb215f8.png">

<img width="985" alt="image" src="https://user-images.githubusercontent.com/208884/50574553-a4b54f00-0db8-11e9-8827-fe5ca43fb0d8.png">

<img width="985" alt="image" src="https://user-images.githubusercontent.com/208884/50574557-a8e16c80-0db8-11e9-9780-ff2da40c7d94.png">

The basic user flow is "enter text; see what language has been flagged."

**Comment by margoyle** [comment]
<img width="682" alt="screen shot 2019-02-09 at 4 26 02 pm" src="https://user-images.githubusercontent.com/6528572/52526507-7ebc7d80-2c87-11e9-95ee-3a4380bc5cc7.png">
State of the UI (full thing in docs>UI>tg_ui_v4.pdf)

**Comment by slifty** [comment]
This issue kind of got forked into #43 (which is now closed)

I think we can close this since the v1 UX is now designed
