### ISSUE TITLE
UX Paradigm exploration

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/truthgoggles#43]
@margoyle is working on the possible UX paradigms, digging a bit deeper than the rough wireframes referenced by #39.

**Comment by margoyle** [comment]
Conclusions of 1/14 discussion of UX paradigm explorations: 
[After adding text to empty screen] begin UI flow with 04 (high level comment view). When a flag is clicked, UI changes to 05 (detailed view of flag info). From here the user can X out to return to the comment view, can click on a 'next' or 'previous' button to advance through the flags in the text, or can edit the flag to resolve it, which will close the detailed view and return to the comment overview. When the user has resolved all the flags they want to resolve, they can advance to a final 'review changes' screen that shows the original text, with flags, and edited text side by side (11).

**Comment by margoyle** [comment]
Some style considerations: 
<img width="580" alt="screen shot 2019-01-20 at 9 14 00 pm" src="https://user-images.githubusercontent.com/6528572/51449112-9479fb00-1cf8-11e9-8dd6-b634f5f1c2d0.png">

**Comment by margoyle** [comment]
<img width="449" alt="screen shot 2019-02-09 at 4 21 36 pm" src="https://user-images.githubusercontent.com/6528572/52526449-d0183d00-2c86-11e9-896a-19f059573e55.png">
Explorations of how selected flags might look in the text editor. Leaning towards E but also like B. 
Full screen views in pdf:  
[selected_flags_variants.pdf](https://github.com/BadIdeaFactory/truthgoggles/files/2848278/selected_flags_variants.pdf)

**Comment by margoyle** [comment]
![tg_button_splash](https://user-images.githubusercontent.com/6528572/52526475-3735f180-2c87-11e9-9c3f-3ef9f169028b.gif)
Exploration for button click 'splash' effect.

**Comment by reefdog** [comment]
Oh that's lovely.

**Comment by reefdog** [comment]
(I'm armchair-observing all this, it looks so great.) Are the various colors/weights/sizes in 
https://github.com/BadIdeaFactory/truthgoggles/issues/43#issuecomment-462080664 representing different ways of indicating intensity of partisanship?

**Comment by margoyle** [comment]
Thanks Justin! They are different ways of indicating which of the highlighted phrases in the text is being viewed in the panel on the right - hopefully clearer in the full view:
<img width="858" alt="screen shot 2019-02-09 at 4 29 27 pm" src="https://user-images.githubusercontent.com/6528572/52526552-0bffd200-2c88-11e9-9328-b9ea333e698d.png">

**Comment by reefdog** [comment]
Oh! That makes sense. 👍

**Comment by margoyle** [comment]
BUT, the different opacities of the highlights is supposed to indicate intensity of partisanship/prevalence of the flag... we might be trying to communicate too many things at once.

**Comment by reefdog** [comment]
(Again, jumping in from the sidelines, so obvs take all this lightly,) Actually I really love the opacity-as-intensity! My personal vote for "selected" would be A; seeing it in a full mockup would verify this suspicion, but I suspect a page full of underlined terms along with a single "full background" term + sidebar would be a very clear "this is selected, but also, you can still see/interact with all the others at full fidelity" mode.

**Comment by reefdog** [comment]
I can also imagine a nice quick animation from "underline" to "background" and back when selecting/deselecting terms.

**Comment by margoyle** [comment]
good point!

**Comment by margoyle** [comment]
Changes based on this morning's discussion. 
<img width="816" alt="screen shot 2019-02-10 at 9 49 00 pm" src="https://user-images.githubusercontent.com/6528572/52544295-f7056a80-2d7d-11e9-9f85-3df717e1602c.png">
Text window, flag highlight, stacked bar graph? (not sure how we'd use a histogram here but let's discuss), partisan language and low relevance tags reduced in size, menu changed to text, and toggle tweaked.

<img width="837" alt="screen shot 2019-02-10 at 9 48 28 pm" src="https://user-images.githubusercontent.com/6528572/52544297-f7056a80-2d7d-11e9-8648-ba4964ad8767.png">
Get info about partisan language and low relevance tags through a tooltip on hover. 

<img width="896" alt="screen shot 2019-02-10 at 9 49 11 pm" src="https://user-images.githubusercontent.com/6528572/52544298-f7056a80-2d7d-11e9-9539-367ad0c6c0d6.png">
Seeing how the highlight works with the red. 

<img width="777" alt="screen shot 2019-02-10 at 9 50 06 pm" src="https://user-images.githubusercontent.com/6528572/52544299-f79e0100-2d7d-11e9-89b3-6ed395ab1ee1.png">
Scroll to discover + arrows.

**Comment by slifty** [comment]
I think we're at a solid version 1 of the UX paradigm -- I'm going to officially mark this as complete!
